SELECT * FROM ATS_LOG WHERE LOG_TYPE = 'EVENT' ORDER BY USER_ID, REG_DATE DESC;

SELECT * FROM ATS_LOG WHERE LOG_TYPE = 'EVENT';

SELECT count(*) FROM ATS_LOG;


SELECT * FROM ATS_GAP_PLAN ORDER BY USER_ID, TOP DESC;

SELECT * FROM ATS_GAP_PLAN WHERE STATE = '1' ORDER BY USER_ID, TOP DESC;



SELECT * FROM ATS_MEMBER;

SELECT * FROM ATS_LOG ORDER BY REG_DATE;

